# Generated by Django 5.0.2 on 2024-07-27 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_person_schoolcourse_schoolgrade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='course',
            field=models.ManyToManyField(blank=True, to='panel.schoolcourse'),
        ),
    ]
