# Generated by Django 5.0.7 on 2024-10-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("panel", "0003_alter_person_course"),
    ]

    operations = [
        migrations.CreateModel(
            name="Data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("email", models.EmailField(max_length=254)),
                ("message", models.TextField()),
            ],
        ),
    ]
