# Generated by Django 5.0.2 on 2024-10-13 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0004_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Data',
        ),
    ]
